name: eslint 
on: [push, pull_request]

jobs:
        linting:
                name: eslint linter
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - uses: actions/setup-node@v1
                          with: 
                                node-version: "12.x"
                        - name: setting up eslint
                          run: | 
                            wget https://raw.githubusercontent.com/standard/eslint-config-standard/master/package.json || npm install eslint-config-standard jest --save-dev [ -f .eslintrc.json ] || wget https://raw.githubusercontent.com/standard/eslint-config-standard/master/eslintrc.json
                        - name: jest report
                          run: npx jest 
                        - name: eslint report
                          run: npx eslint . 

                         
