name: eslint 
on: [push, pull_request]

jobs:
        linting:
                name: eslint linter
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - uses: actions/setup-node@v1
                          with: 
                                node-version: "12.x"
                        - name: setting up eslint
                          run: | 
                             npm install --save-dev eslint eslint-config-airbnb eslint-plugin-import
                             eslint-plugin-react 
                             eslint-plugin-react-hooks || wget https://raw.githubusercontent.com/marcelmokos/eslint-config-with-prettier/master/.eslintrc.yml
                        - name: ESLint Report
                          run: npx eslint .

                         
